Milestone 7: Bootstrap project of newsweek.com
hillarioh/Newsweek.com-clone pull request #1
Opened 2020-04-13 14:35 UTC by hillarioh

This project entails the use of bootstrap to create a clone of the newsweek.com webpage. I have used HTML, CSS, and bootstrap for this project.

2020-04-13 18:16 UTC, majovanilla requested changes
Hi @hillarioh !!

## Good job on this project! 👍

- Good Readme file
- Good Pull Request Message

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Always remember to check your HTML using the [validator](https://validator.w3.org/). You have some errors and warnings. Please fix them.

- You have inline styling in several elements of your HTML file. This is not considered good practice (see more info [here](https://speckyboy.com/good-bad-css-practices/)) Please change the styling to bootstrap classes.

- The borders you use to separate sections have a different color. This happens with the newsletter border (last section), too. Please adjust the color to match the original page.

- Your page is not responsive: you should identify the three main breakpoints and adjust the elements using bootstrap classes. On large screens you are alright, but on the other breakpoints, almost all the sections are like this, when they should have just two columns (medium) and one column(mobile).
**Please make sure your page is responsive before submitting another code review.**
You can use the `col-md-*` `col-lg-*` classes to achieve responsiveness.
Your page changes to mobile after the original page. Please check that, too.
![Screenshot from 2020-04-13 13-11-05](https://user-images.githubusercontent.com/51926937/79146830-965e2d00-7d88-11ea-880a-7b7c4deb11c4.png)

- Check the rest of the comments below.

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- Use semantic HTML in the structure of your HTML file. Favor the use of `<nav>`,    `<main>`,  `<footer>`, `<article>`,  `<section>`, to enclose the elements on your file. You are already using nav, just add the `main` and `footer` to enclose the rest of your elements.

- Your project would look sooo much better if you include the hover effects on the links of the page, like the original version.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-04-13 18:16 UTC, majovanilla commented on style.css
> +}
Remember the purpose of this project: to learn how to use bootstrap classes. Please favor the use of bootstrap classes in all possible cases, like here.

2020-04-13 18:16 UTC, majovanilla commented on style.css
> +  height: 28px;
Remember the purpose of this project: to learn how to use bootstrap classes. Please favor the use of bootstrap classes in all possible cases, like here.

2020-04-13 18:16 UTC, majovanilla commented on index.html
> +        <div
Your page is wider than the original page, this has some unwanted visual effects and element sizing. To achieve the same look you can include a max-width on the div with the container-fluid class.

2020-04-13 18:16 UTC, majovanilla commented on index.html
> +              FEATURED STORIES
The first section (the one before the In magazine section) has three columns. Make sure you are using the correct `col-*` classes, because your first and last columns look smaller than the original page. TIP: there is no need to give a `col-*` class to all columns, just to two of them and the other will take the remaining space.

2020-04-13 18:16 UTC, majovanilla commented on index.html
> +            <div class="d-flex py-1 mb-1 border-bottom">
The images in this section are disproportionated. Please adjust them to be full circles.

2020-04-13 18:16 UTC, majovanilla commented on index.html
> +                />
The more stories images are larger than the original page. Please adjust them and **avoid using the inline styling** You can adjust the width and height using col-* or w-* classes.

2020-04-13 18:16 UTC, majovanilla commented on index.html
> +                />
The first image is not behaving like the original page, please adjust it and **delete the inline styling**
The rest of the images of this section should be taller than wider (vertical rectangle) yours look like a horizontal rectangle. Please adjust them using bootstrap classes.

2020-04-13 18:16 UTC, majovanilla commented on index.html
> +                  alt="Wuhan"
The images in all the categories' sections don't have the right sizing. Please take a look at the original page and adjust this using bootstrap classes.

Also, check the width of each column. Your page has a lot of space between the articles and the three articles on the right side of the sections are wider than they should. Please adjust them using bootstrap classes.

On the mobile version. the three articles on the right should appear below the two articles. Yours don't. Check the image proportions on the mobile version too.
![Screenshot from 2020-04-13 13-09-29](https://user-images.githubusercontent.com/51926937/79146543-2f407880-7d88-11ea-871b-ec688abbb0a5.png)

2020-04-13 18:16 UTC, majovanilla commented on index.html
> +              style="padding-top: 21px; padding-bottom: 13px;"
The elements in this section should be centered on the mobile version. Please adjust this.
Yours:
![Screenshot from 2020-04-13 13-08-12](https://user-images.githubusercontent.com/51926937/79146372-f0aabe00-7d87-11ea-841c-8285a3a73f8c.png)

Original:
![Screenshot from 2020-04-13 13-08-31](https://user-images.githubusercontent.com/51926937/79146383-f43e4500-7d87-11ea-95a1-649114f6fd7f.png)

2020-04-15 07:51 UTC, hillarioh commented
Hi my TSE Consider my level of skills as you review my project, I would appreciate working on improving myself better through your review as you approve my code, Thanks

2020-04-15 09:02 UTC, lekegitrepo commented
### Hi @hillarioh 👏 
### Well done, for implementing some of the requirements mentioned in the previous review. However, most of the requirements mentioned have not been implemented. As mentioned by the previous reviewer:

**_1. Always remember to check your HTML using the validator. You have some errors and warnings. Please fix them._**

**_2. You have inline styling in several elements of your HTML file. This is not considered good practice (see more info here) Please change the styling to bootstrap classes._**

**_3. Your page is not responsive: you should identify the three main breakpoints and adjust the elements using bootstrap classes. On large screens you are alright, but on the other breakpoints, almost all the sections are like this, when they should have just two columns (medium) and one column(mobile). **Try to fix the page responsiveness and make it responsive at each breakpoint like the original**_**

**_4. Fix the subscribe section to make it look like the original._**

**_I'll suggest that you observe the original page and the changes at the breakpoints, maybe that can help_**

### Reviewed by Temitayo Adeleke.

2020-04-15 09:03 UTC, lekegitrepo requested changes
### Status: Request changes

2020-04-15 13:37 UTC, mikenath223 commented
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

2020-04-15 18:06 UTC, mikenath223 commented
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

2020-04-15 18:36 UTC, mikenath223 requested changes
### Hi @hillarioh 👋

You have done quite well on this project.

However, there are changes to be made:

- [ ] Required - Kindly take note of the fact that there is a difference in page structure between yours and the original in the top articles section. The `Featured Stories`, `Top Story` and `Opinion` sections just below the navbar have different structures in the original webpage than what you have in yours. Notice that in the original web page the `Top Story` section comes in between the `Featured Stories` and `Opinion` sections. Kindly make this adjustment in yours.
**THIS IS YOURS**👇
![ice_screenshot_20200415-190845](https://user-images.githubusercontent.com/33323077/79372036-4381a280-7f4d-11ea-808c-5ec5c50eca75.png)

**THIS IS WHAT IS EXPECTED👇**
![ice_screenshot_20200415-190911](https://user-images.githubusercontent.com/33323077/79372065-509e9180-7f4d-11ea-9c0f-a82e40b1ed08.png)

- [ ] Required - Also kindly note that in the original webpage the navbar extends the full width of the page, please ensure yours does the same also.
**THIS IS YOURS**👇
![ice_screenshot_20200415-190749](https://user-images.githubusercontent.com/33323077/79372166-82175d00-7f4d-11ea-9be7-35619d7b92ff.png)

**THIS IS WHAT IS EXPECTED**👇
![ice_screenshot_20200415-190812](https://user-images.githubusercontent.com/33323077/79372204-90657900-7f4d-11ea-873b-d3c7a1da4c3f.png)

- [ ] Required - There is still an issue with responsiveness in your project. On a tablet screen size, the images found in `IN THE MAGAZINE` section, look longer and none-responsive than the original page.
**THIS IS YOURS**👇
![ice_screenshot_20200415-144827](https://user-images.githubusercontent.com/33323077/79373372-63fe2c80-7f4e-11ea-9b6d-dfb31e340812.png)

**THIS IS WHAT IS EXPECTED**👇
![ice_screenshot_20200415-192242](https://user-images.githubusercontent.com/33323077/79375673-e4259180-7f50-11ea-8514-5b563cc0a6c9.png)


- [ ] Required - Also please remove these three images just below the `Featured Slideshow` section. Just the three images at it doesn't appear on the original webpage.
[Screenshot]👇
![ice_screenshot_20200415-145145](https://user-images.githubusercontent.com/33323077/79374630-5c8b5300-7f4f-11ea-988e-84b25d9267d9.png)

- [ ] Also in the footer section there is an overflow of the social links with the logo on a mobile screen size.[Screenshot]👇 
![ice_screenshot_20200415-193107](https://user-images.githubusercontent.com/33323077/79375274-48942100-7f50-11ea-8e01-4a130517e177.png)


- [ ] In addition, kindly remove the inline comments that exist on your code. If you need to refer to a previous version of your code please use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-04-15 22:17 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-04-15 22:29 UTC, addod19 approved these changes
## Status: Approved 🏆 🎈 

Hi @hillarioh, you did a great job fixing all the changes pointed out by the previous TSE's, 👍 now our project looks great, responsive 😄 Your project now meets all the minimum requirements, I hereby approve of your project. Before we merge to master let us consider the following optional comments
[OPTIONAL]
- The height of the ```newsletter``` and ```subscribe``` should be the same
```Currently```
![ts](https://user-images.githubusercontent.com/46388113/79394806-dd564900-7f67-11ea-917d-434000be98f6.PNG)
```Original```
![ts1](https://user-images.githubusercontent.com/46388113/79394842-eb0bce80-7f67-11ea-813e-0d29a6aad4cc.PNG)
```Mobile screen```
```Currently```
![tss1](https://user-images.githubusercontent.com/46388113/79394904-0c6cba80-7f68-11ea-982f-198704285c4d.PNG)
```Original```
![tss](https://user-images.githubusercontent.com/46388113/79394928-168eb900-7f68-11ea-95d8-011c670d7483.PNG)

Go ahead and merge to master, do not forget to complete the project completion form 👍 
_Happy coding_ 👨‍💻 
Good luck with your next projects
Daniel Larbi Addo on slack

2020-04-16 01:09 UTC, merged